name       : kuserfeedback
version    : 1.2.0
release    : 4
source     :
    - https://cdn.download.kde.org/stable/kuserfeedback/kuserfeedback-1.2.0.tar.xz : 76aac922b153249b274680a6f4c72c238ef14e3df04bad00cb64158b1063f264
license    : MIT
component  : desktop.kde.core
optimize   : lto
summary    : Framework for collecting user feedback for applications via telemetry and surveys
description: |
    Framework for collecting user feedback for applications via telemetry and surveys
builddeps  :
    - pkgconfig(Qt5Charts)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - php-devel
setup      : |
    %cmake_ninja -DBUILD_TEST=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
